core/urls.py
from django.urls import path
from core import views

urlpatterns = [
    path("", views.HomeView.as_view(), name="home")
]

courses/urls.py
from django.urls import path
from courses import views

urlpatterns = [
    # Courses views
    path("create/", views.CourseCreateView.as_view(), name="course-create"),
    path("<int:pk>/", views.CourseHomeView.as_view(), name="course-detail"),
    path("<int:pk>/update/", views.CourseUpdateView.as_view(), name="course-update"),
    path("<int:pk>/delete/", views.CourseDeleteView.as_view(), name="course-delete"),

    path("join/", views.JoinCourseView.as_view(), name="join-course"),
    path("leave/<int:pk>/", views.LeaveCourseView.as_view(), name="leave-course"),

    path("student-courses/", views.StudentCourses.as_view(), name="student-courses"),
    path("teacher-courses/", views.TeacherCourses.as_view(), name="teacher-courses"),

    # Module views
    path("<int:pk>/module-create/", views.ModuleCreateView.as_view(), name="module-create"),
    path("module/<int:pk>/update/", views.ModuleUpdateView.as_view(), name="module-update"),
    path("module/<int:pk>/delete/", views.ModuleDeleteView.as_view(), name="module-delete"),

    # Lesson views
    path("module/<int:pk>/lesson-create/", views.LessonCreateView.as_view(), name="lesson-create"),
    path("lesson/<int:pk>/", views.LessonDetailView.as_view(), name="lesson-detail"),
    path("lesson/<int:pk>/update/", views.LessonUpdateView.as_view(), name="lesson-update"),
    path("lesson/<int:pk>/delete/", views.LessonDeleteView.as_view(), name="lesson-delete"),

    # Material views
    path("lesson/<int:pk>/materials-create/", views.MaterialsCreateView.as_view(), name="materials-create"),
    path("material/<int:pk>/delete/", views.MaterialDeleteView.as_view(), name="material-delete"),

    # Task views
    path("lesson/<int:pk>/task-create/", views.TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/update/", views.TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/", views.TaskDeleteView.as_view(), name="task-delete"),
    path("task/<int:pk>/completions/", views.TaskCompletionsView.as_view(), name="task-completions"),

    # Completions views
    path("task/<int:pk>/complete/", views.CompletionCreateView.as_view(), name="completion-create"),
    path("task/<int:pk>/delete-completion/", views.CompletionDeleteView.as_view(), name="completion-delete"),

    # Grade views
    path("completion/<int:pk>/grade/", views.GradeCompletionView.as_view(), name="grade-completion"),
    path("grade/<int:pk>/delete/", views.GradeDeleteView.as_view(), name="grade-delete")
]

app_name = "courses"

learning_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('courses/', include("courses.urls")),
    path('', include("core.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.views.generic import ListView
from django.contrib.auth import get_user_model
from courses.models import Course

User = get_user_model()

# Create your views here.
class HomeView(ListView):
    model = Course
    context_object_name = "courses"
    template_name = "core/home.html"

    def get_queryset(self):
        if self.request.user.role == "teacher":
            return Course.objects.filter(teacher=self.request.user)
        else:
            return Course.objects.filter(students=self.request.user)

templates/core/home.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid h-100">
    
    {% if courses %}
        <div class="row row-cols-1 row-cols-md-3 g-3">
            {% for course in courses %}
                <div class="col">
                    <div class="card text-bg-{{course.color}} rounded" style="height: 30vh;">
                        <div class="d-flex flex-column justify-content-end h-100 py-3 px-4">
                            <a href="{% url 'courses:course-detail' course.pk %}" class="h2 link-light link-underline link-offset-2 link-offset-2-hover link-underline-opacity-0 link-underline-opacity-100-hover mb-1">{{course.name}}</a>
                            {% if request.user.role != "teacher" %}
                                <h4 class="fw-normal text-white">{{course.teacher.username}}</h4>
                            {% else %}
                                <span> </span>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="d-flex justify-content-center align-items-center w-100 h-100">
            <h3>
                {% if request.user.role == "teacher" %}
                    Ви не створили жодного курсу                
                {% else %}
                    Ви не приєдналися до жодного з курсів
                {% endif %}
            </h3>
        </div>
    {% endif %}
</div>
{% endblock %}