account/urls.py
from django.urls import path
from account import views

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("register/", views.RegistrationView.as_view(), name="register"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("account-update/", views.AccountUpdateView.as_view(), name="account-update")
]

app_name = "account"

core/urls.py
from django.urls import path
from core import views

urlpatterns = [
    path("", views.HomeView.as_view(), name="home")
]

courses/urls.py
from django.urls import path
from courses import views

urlpatterns = [
    # Courses views
    path("create/", views.CourseCreateView.as_view(), name="course-create"),
    path("<int:pk>/", views.CourseHomeView.as_view(), name="course-detail"),
    path("<int:pk>/update/", views.CourseUpdateView.as_view(), name="course-update"),
    path("<int:pk>/delete/", views.CourseDeleteView.as_view(), name="course-delete"),

    path("join/", views.JoinCourseView.as_view(), name="join-course"),
    path("leave/<int:pk>/", views.LeaveCourseView.as_view(), name="leave-course"),

    path("student-courses/", views.StudentCourses.as_view(), name="student-courses"),
    path("teacher-courses/", views.TeacherCourses.as_view(), name="teacher-courses"),

    # Module views
    path("<int:pk>/module-create/", views.ModuleCreateView.as_view(), name="module-create"),
    path("module/<int:pk>/update/", views.ModuleUpdateView.as_view(), name="module-update"),
    path("module/<int:pk>/delete/", views.ModuleDeleteView.as_view(), name="module-delete"),

    # Lesson views
    path("module/<int:pk>/lesson-create/", views.LessonCreateView.as_view(), name="lesson-create"),
    path("lesson/<int:pk>/", views.LessonDetailView.as_view(), name="lesson-detail"),
    path("lesson/<int:pk>/update/", views.LessonUpdateView.as_view(), name="lesson-update"),
    path("lesson/<int:pk>/delete/", views.LessonDeleteView.as_view(), name="lesson-delete"),

    # Material views
    path("lesson/<int:pk>/materials-create/", views.MaterialsCreateView.as_view(), name="materials-create"),
    path("material/<int:pk>/delete/", views.MaterialDeleteView.as_view(), name="material-delete"),

    # Task views
    path("lesson/<int:pk>/task-create/", views.TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/update/", views.TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/", views.TaskDeleteView.as_view(), name="task-delete"),
    path("task/<int:pk>/completions/", views.TaskCompletionsView.as_view(), name="task-completions"),

    # Completions views
    path("task/<int:pk>/complete/", views.CompletionCreateView.as_view(), name="completion-create"),
    path("task/<int:pk>/delete-completion/", views.CompletionDeleteView.as_view(), name="completion-delete"),

    # Grade views
    path("completion/<int:pk>/grade/", views.GradeCompletionView.as_view(), name="grade-completion"),
    path("grade/<int:pk>/delete/", views.GradeDeleteView.as_view(), name="grade-delete")
]

app_name = "courses"

learning_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('courses/', include("courses.urls")),
    path('', include("core.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>LMS</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    {% include 'navbar.html' %}
    <div class="d-flex w-100 h-100 mt-5" style="min-height: 93vh;">
        <div class="border-end" style="width: 20%;">
            <a href="{% url 'home' %}" class="btn btn-light rounded-pill rounded-start text-start text-decoration-none my-2 ps-4" style="width: 90%;">
                <div class="d-flex align-items-center gap-3">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
                        <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293zM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5z"/>
                    </svg>
                    Головна
                </div>
            </a>
            <div class="border border-start-0 border-end-0">
                <div class="accordion">
                    <div class="accordion-item border-0">
                        <div class="accordion-header">
                            <button type="button" class="accordion-button collapsed btn bg-light rounded-pill rounded-start text-start text-decoration-none my-2 py-2 ps-4" data-bs-toggle="collapse" data-bs-target="#courses" aria-controls="courses" style="width: 90%;">
                                <div class="d-flex align-items-center gap-3">
                                    {% if request.user.role == "student" %}
                                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-book-half" viewBox="0 0 16 16">
                                            <path d="M8.5 2.687c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783"/>
                                        </svg>
                                    {% else %}
                                        <!-- <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-people-fill" viewBox="0 0 16 16">
                                            <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6m-5.784 6A2.24 2.24 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.3 6.3 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1zM4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5"/>
                                        </svg> -->
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512" width="20" height="20">!Font Awesome Free 6.6.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.<path d="M320 32c-8.1 0-16.1 1.4-23.7 4.1L15.8 137.4C6.3 140.9 0 149.9 0 160s6.3 19.1 15.8 22.6l57.9 20.9C57.3 229.3 48 259.8 48 291.9l0 28.1c0 28.4-10.8 57.7-22.3 80.8c-6.5 13-13.9 25.8-22.5 37.6C0 442.7-.9 448.3 .9 453.4s6 8.9 11.2 10.2l64 16c4.2 1.1 8.7 .3 12.4-2s6.3-6.1 7.1-10.4c8.6-42.8 4.3-81.2-2.1-108.7C90.3 344.3 86 329.8 80 316.5l0-24.6c0-30.2 10.2-58.7 27.9-81.5c12.9-15.5 29.6-28 49.2-35.7l157-61.7c8.2-3.2 17.5 .8 20.7 9s-.8 17.5-9 20.7l-157 61.7c-12.4 4.9-23.3 12.4-32.2 21.6l159.6 57.6c7.6 2.7 15.6 4.1 23.7 4.1s16.1-1.4 23.7-4.1L624.2 182.6c9.5-3.4 15.8-12.5 15.8-22.6s-6.3-19.1-15.8-22.6L343.7 36.1C336.1 33.4 328.1 32 320 32zM128 408c0 35.3 86 72 192 72s192-36.7 192-72L496.7 262.6 354.5 314c-11.1 4-22.8 6-34.5 6s-23.5-2-34.5-6L143.3 262.6 128 408z"/></svg>
                                    {% endif %}
                                    Мої курси
                                </div>
                            </button>
                        </div>
                        <div class="accordion-collapse collapse" id="courses">
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="py-3 overflow-y-auto" style="width: 80%; max-height: 93vh;">
            {% block content %}
            
            {% endblock %}
        </div>
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script>
        fetch("{% if request.user.is_staff %}{% url 'courses:teacher-courses' %}{% else %}{% url 'courses:student-courses' %}{% endif %}", {
            headers: {
                'X-Requested-With': 'XMLHttpRequest'
            }
        })
        .then(response => {
            console.log(response)
            if (!response.ok) {
                throw new Error('Network response was not ok ' + response.statusText);
            }
            return response.text();
        })
        .then(data => {
            document.getElementById("courses").innerHTML = data;
        });

        const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]');
        const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl));
    </script>
</body>
</html>

templates/navbar.html
<nav class="navbar fixed-top bg-white border-bottom py-0">
    <div class="container-fluid px-4">
        <div>
            <a href="{% url 'home' %}" class="navbar-brand link fs-4 me-0">
                <div class="d-flex align-items-center gap-2">
                    <!-- <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">!Font Awesome Free 6.6.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.<path d="M390.9 298.5c0 0 0 .1 .1 .1c9.2 19.4 14.4 41.1 14.4 64C405.3 445.1 338.5 512 256 512s-149.3-66.9-149.3-149.3c0-22.9 5.2-44.6 14.4-64h0c1.7-3.6 3.6-7.2 5.6-10.7c4.4-7.6 9.4-14.7 15-21.3c27.4-32.6 68.5-53.3 114.4-53.3c33.6 0 64.6 11.1 89.6 29.9c9.1 6.9 17.4 14.7 24.8 23.5c5.6 6.6 10.6 13.8 15 21.3c2 3.4 3.8 7 5.5 10.5zm26.4-18.8c-30.1-58.4-91-98.4-161.3-98.4s-131.2 40-161.3 98.4L0 202.7 256 0 512 202.7l-94.7 77.1z"/></svg> -->
                    Learning system
                </div>
            </a>
        </div>

        <span class="fw-semibold">
            {% if request.user.role == "teacher" %}
                Teacher version
            {% else %}
                Student version
            {% endif %}
        </span>

        <div class="d-flex align-items-center gap-3">
            {% if request.user.role == "teacher" %}
                <a href="{% url 'courses:course-create' %}" class="btn btn-light rounded-circle p-0" title="Створити курс">
                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
                        <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"/>
                    </svg>
                </a>
            {% else %}
                <button type="button" class="btn btn-light rounded-circle p-0" data-bs-toggle="modal" data-bs-target="#exampleModal" title="Приєднатись до курсу">
                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
                        <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"/>
                    </svg>
                </button>
            {% endif %}
            
            <a href="{% url 'account:profile' %}" class="btn btn-light rounded-circle p-1">
                {% if request.user.profile.picture %}
                    <img src="{{request.user.profile.picture.url}}" class="rounded-circle" width="38" height="38" alt="">
                {% else %}
                    <svg xmlns="http://www.w3.org/2000/svg" class="bg-body rounded-circle" width="38" height="38" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                        <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
                    </svg>
                {% endif %}
            </a>
        </div>
    </div>
</nav>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
        <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Приєднатись до курсу</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form action="{% url 'courses:join-course' %}" method="post">
                {% csrf_token %}
                <p>
                    <label class="form-label" for="join_code">Код курсу:</label>
                    <input type="text" maxlength="8" name="join_code" class="form-control">
                </p>
                <button type="submit" class="btn btn-primary">Приєднатись</button>
            </form>
        </div>
        </div>
    </div>
</div>