core/urls.py
from django.urls import path
from core import views

urlpatterns = [
    path("", views.HomeView.as_view(), name="home")
]

courses/urls.py
from django.urls import path
from courses import views

urlpatterns = [
    # Courses views
    path("create/", views.CourseCreateView.as_view(), name="course-create"),
    path("<int:pk>/", views.CourseHomeView.as_view(), name="course-detail"),
    path("<int:pk>/update/", views.CourseUpdateView.as_view(), name="course-update"),
    path("<int:pk>/delete/", views.CourseDeleteView.as_view(), name="course-delete"),

    path("join/", views.JoinCourseView.as_view(), name="join-course"),
    path("leave/<int:pk>/", views.LeaveCourseView.as_view(), name="leave-course"),

    path("student-courses/", views.StudentCourses.as_view(), name="student-courses"),
    path("teacher-courses/", views.TeacherCourses.as_view(), name="teacher-courses"),

    # Module views
    path("<int:pk>/module-create/", views.ModuleCreateView.as_view(), name="module-create"),
    path("module/<int:pk>/update/", views.ModuleUpdateView.as_view(), name="module-update"),
    path("module/<int:pk>/delete/", views.ModuleDeleteView.as_view(), name="module-delete"),

    # Lesson views
    path("module/<int:pk>/lesson-create/", views.LessonCreateView.as_view(), name="lesson-create"),
    path("lesson/<int:pk>/", views.LessonDetailView.as_view(), name="lesson-detail"),
    path("lesson/<int:pk>/update/", views.LessonUpdateView.as_view(), name="lesson-update"),
    path("lesson/<int:pk>/delete/", views.LessonDeleteView.as_view(), name="lesson-delete"),

    # Material views
    path("lesson/<int:pk>/materials-create/", views.MaterialsCreateView.as_view(), name="materials-create"),
    path("material/<int:pk>/delete/", views.MaterialDeleteView.as_view(), name="material-delete"),

    # Task views
    path("lesson/<int:pk>/task-create/", views.TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/update/", views.TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/", views.TaskDeleteView.as_view(), name="task-delete"),
    path("task/<int:pk>/completions/", views.TaskCompletionsView.as_view(), name="task-completions"),

    # Completions views
    path("task/<int:pk>/complete/", views.CompletionCreateView.as_view(), name="completion-create"),
    path("task/<int:pk>/delete-completion/", views.CompletionDeleteView.as_view(), name="completion-delete"),

    # Grade views
    path("completion/<int:pk>/grade/", views.GradeCompletionView.as_view(), name="grade-completion"),
    path("grade/<int:pk>/delete/", views.GradeDeleteView.as_view(), name="grade-delete")
]

app_name = "courses"

learning_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('courses/', include("courses.urls")),
    path('', include("core.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/models.py
from typing import Any
from django.db import models
from django.contrib.auth import get_user_model
import random
import string

User = get_user_model()

def course_color():
    COLOR_CHOICES = [
        "danger",
        "primary",
        "success",
        "info",
        "dark"
    ]

    return random.choice(COLOR_CHOICES)


# Create your models here.
class Course(models.Model):
    COLOR_CHOICES = (
        ("danger", "червоний"),
        ("primary", "синій"),
        ("success", "зелений"),
        ("info", "голубий"),
        ("dark", "чорний")
    )

    name = models.CharField(max_length=255)
    description = models.TextField()
    teacher = models.ForeignKey(User, on_delete=models.CASCADE, related_name="teacher_courses", limit_choices_to={"role": "teacher"})
    students = models.ManyToManyField(
        User,
        related_name="student_courses", 
        limit_choices_to={"role": "student"}, 
        blank=True
    )
    color = models.CharField(default=course_color, choices=COLOR_CHOICES, max_length=10)

    @property
    def join_code(self):
        random.seed(self.pk)
        characters = string.ascii_letters + string.digits

        code = "".join(random.choice(characters) for _ in range(8))
        return code

    def __str__(self):
        return self.name


class Module(models.Model):
    name = models.CharField(max_length=255)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="modules")

    def __str__(self):
        return self.name


class Lesson(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    module = models.ForeignKey(Module, on_delete=models.CASCADE, related_name="lessons")

    def delete(self, *args, **kwargs):
        for material in self.materials.all():
            material.delete()

        return super(Lesson, self).delete(*args, **kwargs)

    @property
    def course(self):
        return self.module.course

    def __str__(self):
        return self.title


class Material(models.Model):
    file = models.FileField(upload_to="materials/")
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, related_name="materials")

    @property
    def name(self):
        return self.file.name.split("/")[-1]

    def delete(self, *args, **kwargs):
        self.file.delete(False)

        return super().delete(*args, **kwargs)

    def __str__(self) -> str:
        return f"{self.lesson} - {self.file.name}"


class Task(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, related_name="tasks")

    def __str__(self) -> str:
        return self.name
    
    @property
    def students(self):
        return [completion.student for completion in Completion.objects.filter(task=self)]


class Completion(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE, limit_choices_to={"role": "student"})
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name="completions")
    text = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def delete(self, *args, **kwargs):
        for completion_file in self.files.all():
            completion_file.delete()

        return super(Completion, self).delete(*args, **kwargs)

    def __str__(self) -> str:
        return f"{self.task} - {self.student}"


class CompletionFile(models.Model):
    file = models.FileField(upload_to="completions/")
    completion = models.ForeignKey(Completion, on_delete=models.CASCADE, related_name="files")

    def delete(self, *args, **kwargs):
        self.file.delete(False)
        return super(CompletionFile, self).delete(*args, **kwargs)
    
    @property
    def name(self):
        return self.file.name.split("/")[-1]

    def __str__(self) -> str:
        return self.file.name


class Grade(models.Model):
    value = models.PositiveIntegerField(default=0)
    completion = models.OneToOneField(Completion, on_delete=models.CASCADE, related_name="grade")

    def __str__(self) -> str:
        return f"{self.completion}: {self.value}"

courses/forms.py
from typing import Any
from django import forms
from courses.models import Completion, CompletionFile

class CompletionForm(forms.ModelForm):
    class Meta:
        model = Completion
        fields = ["task", "text"]

    def save(self, commit: bool = ...) -> Any:
        instance =  super().save(commit)

        for file in self.files:
            CompletionFile.objects.create(file=file, completion=instance)

        return instance

courses/views.py
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect, render
from django.views.generic import CreateView, DetailView, DeleteView, UpdateView, ListView, View
from courses import mixins
from courses.forms import CompletionForm
from courses.models import Course, Module, Lesson, Material, Completion, CompletionFile, Task, Grade

# Create your views here.
class CourseCreateView(mixins.UserIsTeacher, CreateView):
    model = Course
    fields = ["name", "description"]
    template_name = "courses/course_create.html"

    def form_valid(self, form):
        form.instance.teacher = self.request.user

        self.object = form.instance
        return super().form_valid(form)
    
    def get_success_url(self) -> str:
        return reverse_lazy("courses:course-detail", kwargs={"pk": self.object.pk})
    

class CourseDeleteView(mixins.TeacherIsCourseOwner, DeleteView):
    model = Course
    http_method_names = ["post"]
    success_url = reverse_lazy("home")


class CourseUpdateView(mixins.TeacherIsCourseOwner, UpdateView):
    model = Course
    fields = ["name", "description", "color"]
    context_object_name = "course"
    template_name = "courses/course_update.html"
    
    def get_success_url(self) -> str:
        course = self.get_object()
        return reverse_lazy("courses:course-detail", kwargs={"pk": course.pk})


class CourseHomeView(DetailView):
    model = Course
    context_object_name = "course"
    template_name = "courses/course_home.html"

    def get_template_names(self) -> list[str]:
        if self.get_object().teacher == self.request.user:
            return ["courses/teacher_course_home.html"]
        
        return super().get_template_names()


class JoinCourseView(View):
    http_method_names = ["post"]

    def post(self, *args, **kwargs):
        join_code = self.request.POST.get("join_code")

        course: Course = list(filter(lambda course: course.join_code == join_code, Course.objects.all()))[0]
        course.students.add(self.request.user)

        return redirect(reverse_lazy("courses:course-detail", kwargs={"pk": course.pk}))


class LeaveCourseView(mixins.UserIsCourseStudent, View):
    http_method_names = ["post"]

    def get_course(self):
        return Course.objects.get(pk=self.kwargs.get("pk"))

    def post(self, *args, **kwargs):
        course = self.get_course()

        course.students.remove(self.request.user)

        return redirect("home")
    

class StudentCourses(View):
    def get(self, *args, **kwargs):
        if self.request.headers.get('x-requested-with') == "XMLHttpRequest":
            courses = Course.objects.filter(students=self.request.user)
            context = {"courses": courses}

            return render(self.request, "courses/user_courses.html", context=context)
        else:
            raise PermissionDenied
        

class TeacherCourses(View):
    def get(self, *args, **kwargs):
        if self.request.headers.get('x-requested-with') == "XMLHttpRequest":
            courses = Course.objects.filter(teacher=self.request.user)
            context = {"courses": courses}

            return render(self.request, "courses/user_courses.html", context=context)
        else:
            raise PermissionDenied


class ModuleCreateView(mixins.TeacherIsCourseOwner, CreateView):
    model = Module
    fields = ["name"]
    http_method_names = ["post"]

    def get_object(self):
        return Course.objects.get(pk=self.kwargs.get("pk"))

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        form.instance.course = self.get_object()

        return super().form_valid(form)

    def get_success_url(self) -> str:
        course = Course.objects.get(pk=self.kwargs.get("pk"))
        return reverse_lazy("courses:course-detail", kwargs={"pk": course.pk})


class ModuleUpdateView(mixins.TeacherIsCourseOwner, UpdateView):
    model = Module
    fields = ["name"]
    http_method_names = ["post"]

    def get_success_url(self) -> str:
        return reverse_lazy("courses:course-detail", kwargs={"pk": self.get_object().course.pk})


class ModuleDeleteView(mixins.TeacherIsCourseOwner, DeleteView):
    model = Module
    http_method_names = ["post"]

    def get_success_url(self) -> str:
        return reverse_lazy("courses:course-detail", kwargs={"pk": self.get_object().course.pk})


class LessonCreateView(mixins.TeacherIsCourseOwner, CreateView):
    model = Lesson
    fields = ["title", "description"]
    template_name = "courses/lesson_create.html"

    def get_object(self) -> Model:
        return Module.objects.get(pk=self.kwargs.get("pk"))

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        form.instance.module = self.get_object()

        self.object = form.instance
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["module"] = self.get_object()

        return context

    def get_success_url(self) -> str:
        return reverse_lazy("courses:lesson-detail", kwargs={"pk": self.object.pk})


class LessonDetailView(DetailView):
    model = Lesson
    context_object_name = "lesson"
    template_name = "courses/lesson_detail.html"

    def get_template_names(self) -> list[str]:
        if self.request.user.role == "teacher":
            return ["courses/teacher_lesson_detail.html"]

        return super().get_template_names()


class LessonDeleteView(mixins.TeacherIsCourseOwner, DeleteView):
    model = Lesson
    http_method_names = ["post"]

    def get_success_url(self) -> str:
        return reverse_lazy("courses:course-detail", kwargs={"pk": self.get_object().course.pk})
    

class LessonUpdateView(mixins.TeacherIsCourseOwner, UpdateView):
    model = Lesson
    fields = ["title", "description"]
    context_object_name = "lesson"
    template_name = "courses/lesson_update.html"

    def get_success_url(self) -> str:
        return reverse_lazy("courses:lesson-detail", kwargs={"pk": self.get_object().pk})


class MaterialsCreateView(mixins.TeacherIsCourseOwner, View):
    http_method_names = ["post"]

    def get_object(self):
        return Lesson.objects.get(pk=self.kwargs.get("pk"))

    def post(self, *args, **kwargs):
        lesson = self.get_object()

        for file in self.request.FILES.getlist("files"):
            Material.objects.create(lesson=lesson, file=file)

        return redirect(reverse_lazy("courses:lesson-detail", kwargs={"pk": lesson.pk}))


class MaterialDeleteView(mixins.TeacherIsCourseOwner, DeleteView):
    model = Material
    http_method_names = ["post"]

    def get_success_url(self) -> str:
        return reverse_lazy("courses:lesson-detail", kwargs={"pk": self.get_object().lesson.pk})
    

class TaskCreateView(mixins.TeacherIsCourseOwner, CreateView):
    model = Task
    fields = ["name", "description"]
    http_method_names = ["post"]

    def get_object(self) -> Model:
        return Lesson.objects.get(pk=self.kwargs.get("pk"))

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        form.instance.lesson = self.get_object()

        if form.instance.lesson.course.teacher != self.request.user:
            raise PermissionDenied

        return super().form_valid(form)
    
    def get_success_url(self) -> str:
        return reverse_lazy("courses:lesson-detail", kwargs={"pk": self.kwargs.get("pk")})


class TaskUpdateView(mixins.TeacherIsCourseOwner, UpdateView):
    model = Task
    fields = ["name", "description"]
    http_method_names = ["post"]

    def get_success_url(self) -> str:
        return reverse_lazy("courses:lesson-detail", kwargs={"pk": self.get_object().lesson.pk})


class TaskDeleteView(mixins.TeacherIsCourseOwner, DeleteView):
    model = Task
    http_method_names = ["post"]

    def get_success_url(self) -> str:
        return reverse_lazy("courses:lesson-detail", kwargs={"pk": self.get_object().lesson.pk})


class TaskCompletionsView(mixins.TeacherIsCourseOwner, ListView):
    model = Completion
    context_object_name = "completions"
    template_name = "courses/task_completions.html"
    allow_empty = True

    def get_object(self):
        return Task.objects.get(pk=self.kwargs.get("pk"))

    def get_queryset(self):
        return Completion.objects.filter(task=self.get_object())
    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)

        context["task"] = self.get_object()

        return context


class CompletionCreateView(mixins.UserIsCourseStudent, CreateView):
    model = Completion
    fields = ["text"]
    http_method_names = ["post"]

    def get_course(self):
        return Task.objects.get(pk=self.kwargs.get("pk")).lesson.course

    def get_success_url(self) -> str:
        task = Task.objects.get(pk=self.kwargs.get("pk"))

        return reverse_lazy("courses:lesson-detail", kwargs={"pk": task.lesson.pk})

    def form_valid(self, form: BaseModelForm):
        if self.model.objects.filter(task=self.get_task(), student=self.request.user).exists():
            return HttpResponse(status=409)

        form.instance = form.save(commit=False)

        form.instance.student = self.request.user
        form.instance.task = self.get_task()
        
        completion = form.save(commit=True)

        for file in self.request.FILES.getlist("files"):
            CompletionFile.objects.create(completion=completion, file=file)

        return super().form_valid(form)
    

class CompletionDeleteView(DeleteView):
    model = Completion
    http_method_names = ["post"]
    
    def get_task(self):
        return Task.objects.get(pk=self.kwargs.get("pk"))
    
    def get_object(self) -> Model:

templates/courses/course_create.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <form action="{% url 'courses:course-create' %}" method="post">
        {% csrf_token %}
        <input type="text" name="name" value="{{course.name}}" placeholder="Назва курсу" class="form-control fs-2">

        <div class="d-flex gap-3 mt-3">
            <div class="d-flex flex-column w-25 gap-3">
                <div class="card">
                    <div class="card-header">
                        <h4>Про курс</h4>
                    </div>
                    <div class="card-body">
                        <textarea name="description" id="" class="form-control" style="resize: vertical;">{{course.description}}</textarea>
                    </div>
                </div>

                <button type="submit" class="btn btn-primary w-100">Створити курс</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

templates/courses/course_update.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <form action="{% url 'courses:course-update' course.pk %}" method="post">
        {% csrf_token %}
        <input type="text" name="name" value="{{course.name}}" placeholder="Назва курсу" class="form-control fs-2">

        <div class="d-flex gap-3 mt-3">
            <div class="d-flex flex-column w-25 gap-3">
                <div class="card">
                    <div class="card-header">
                        <h4>Про курс</h4>
                    </div>
                    <textarea name="description" id="" class="form-control border border-0" style="resize: vertical;">{{course.description}}</textarea>
                </div>

                <div class="card">
                    <div class="card-header">
                        <h4>Колір курсу</h4>
                    </div>
                    <select class="form-control border border-0" name="color" id="color">
                        <option value="{{course.color}}" hidden>{{course.get_color_display}}</option>
                        <option value="danger">червоний</option>
                        <option value="primary">синій</option>
                        <option value="success">зелений</option>
                        <option value="info">голубий</option>
                        <option value="dark">чорний</option>
                    </select>
                </div>
                
                <button type="submit" class="btn btn-outline-success w-100">
                    <div class="d-flex justify-content-center align-items-center gap-2">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-floppy-fill" viewBox="0 0 16 16">
                            <path d="M0 1.5A1.5 1.5 0 0 1 1.5 0H3v5.5A1.5 1.5 0 0 0 4.5 7h7A1.5 1.5 0 0 0 13 5.5V0h.086a1.5 1.5 0 0 1 1.06.44l1.415 1.414A1.5 1.5 0 0 1 16 2.914V14.5a1.5 1.5 0 0 1-1.5 1.5H14v-5.5A1.5 1.5 0 0 0 12.5 9h-9A1.5 1.5 0 0 0 2 10.5V16h-.5A1.5 1.5 0 0 1 0 14.5z"/>
                            <path d="M3 16h10v-5.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5zm9-16H4v5.5a.5.5 0 0 0 .5.5h7a.5.5 0 0 0 .5-.5zM9 1h2v4H9z"/>
                        </svg>
                        Зберегти зміни
                    </div>
                </button>
                <a href="{% url 'courses:course-detail' course.pk %}" class="btn btn-secondary">
                    <div class="d-flex justify-content-center align-items-center gap-2">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-lg" viewBox="0 0 16 16">
                            <path d="M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8z"/>
                        </svg>
                        Відхилити зміни
                    </div>
                </a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

templates/courses/lesson_create.html
{% extends 'base.html' %}

{% load completion %}
{% block content %}
<div class="container">
    <div class="d-flex justify-content-center gap-3">
        <form action="{% url 'courses:lesson-create' module.pk %}" method="post" class="w-75">
            {% csrf_token %}
            <label for="title">Назва: </label>
            <input type="text" name="title" id="title" class="form-control" required>
            <hr>
            <p>
                <label for="description">Опис: </label>
                <textarea name="description" id="description" class="form-control" required></textarea>
            </p>

            <button type="submit" class="btn btn-primary w-100">Створити урок</button>
        </form>
    </div>
</div>
{% endblock %}

templates/courses/task_completions.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="card mb-4">
        <h3 class="card-header text-bg-primary">{{task.name}}</h3>
        <div class="card-body">
            {{task.description}}
        </div>
        <div class="card-footer">
            <div class="d-flex justify-content-between align-items-center">
                <span>
                    Робіт надіслано: <b>{{completions|length}}</b>
                </span>
                <a href="{% url 'courses:lesson-detail' task.lesson.pk %}" class="btn btn-info">Повернутись до урока</a>
            </div>
        </div>
    </div>

    <h2 class="text-center w-100">Роботи учнів</h2>
    {% for completion in completions %}
        <div class="text-bg-light border rounded-1 p-2 fs-5">
            <div class="d-flex justify-content-between align-items-center px-3 position-relative">
                <div class="d-flex align-items-center gap-2">
                    {% if completion.student.profile.picture %}
                        <img src="{{completion.student.profile.picture.url}}" class="rounded-circle" width="32" height="32" alt="">
                    {% else %}
                        <svg xmlns="http://www.w3.org/2000/svg" class="bg-body rounded-circle" width="32" height="32" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                            <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
                        </svg>
                    {% endif %}
                    {{completion.student.username}}
                </div>

                <div class="position-absolute top-50 start-50 translate-middle">
                    {{completion.created_at|date:"H:i d.m.Y"}}
                </div>
                
                <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#completion{{completion.pk}}">Дивитись роботу</button>
            </div>
        </div>
    
        <div class="modal fade" tabindex="-1" id="completion{{completion.pk}}" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-xl">
                <div class="modal-content" style="height: 90vh;">
                    <div class="modal-header text-bg-success">
                        <h3>{{completion.student.username}}</h3>
                        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close" style="opacity: 1 !important;"></button>
                    </div>
                    <div class="modal-body overflow-y-auto px-3">
                        <p class="modal-text">
                            {{completion.text}}
                        </p>

                        {% if completion.text and completion.files.exists %}
                            <hr>
                        {% endif %}

                        {% if completion.files.exists %}
                            <div class="d-grid gap-1">
                                {% for file in completion.files.all %}
                                    <a href="{{file.file.url}}" class="btn btn-dark w-100" download>
                                        <div class="d-flex align-items-center gap-1">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-file-earmark-arrow-down" viewBox="0 0 16 16">
                                                <path d="M8.5 6.5a.5.5 0 0 0-1 0v3.793L6.354 9.146a.5.5 0 1 0-.708.708l2 2a.5.5 0 0 0 .708 0l2-2a.5.5 0 0 0-.708-.708L8.5 10.293z"/>
                                                <path d="M14 14V4.5L9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2M9.5 3A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5z"/>
                                            </svg>
                                            <span class="fw-semibold">
                                                {{file.name}}
                                            </span>
                                        </div>
                                    </a>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                    <div class="modal-footer fs-5">
                        <div class="d-flex justify-content-between align-items-center w-100">
                            {% if completion.grade %}
                                <span>
                                    Оцінено: <b>{{completion.grade.value}}</b>
                                </span>
    
                                <form action="{% url 'courses:grade-delete' completion.grade.pk %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger">Видалити оцінку</button>
                                </form>
                            {% else %}
                                <div class="d-flex align-items-center gap-3 w-25">
                                    <label for="value">Оцінити: </label>
                                    <input type="number" class="form-control" name="value" id="value" value="0" min="0" form="grade-completion" required>
                                </div>
    
                                <form action="{% url 'courses:grade-completion' completion.pk %}" method="post" id="grade-completion">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-primary">Оцінити</button>
                                </form>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

templates/courses/user_courses.html
<ul class="list-group mb-2">
    {% for course in courses %}
        <a href="{% url 'courses:course-detail' course.pk %}" class="list-group-item list-group-action btn bg-{{course.color}} text-white rounded-pill rounded-start text-start text-decoration-none py-2 ps-4" style="width: 75%; margin-bottom: 3px;">
            <span class="fw-semibold">{{course.name}}</span>
        </a>
    {% endfor %}
</ul>